#!/usr/bin/env bash
# Translate the flight sheet into a config the runner can source.
#
# Hive calls this on every start. The fields a rig owner fills in are:
#
#   Wallet       -> $CUSTOM_TEMPLATE   the coldkey wallet name, e.g. "miner"
#   Pool URL     -> $CUSTOM_URL        the chain RPC, blank means mainnet
#   Extra config -> $CUSTOM_USER_CONFIG  KEY=VALUE lines, see below
#
# Everything a rig needs beyond that is derived, not asked for: one hotkey per
# card, one model per card sized from its VRAM, one axon port per card. Asking a
# rig owner to fill twelve rows by hand is how a flight sheet gets abandoned.
#
# Recognised keys in "Extra config arguments":
#
#   GPUS=0,2,5              cards to use, default every card
#   HOTKEY_PREFIX=expert    hotkey N is <prefix><N+1>, default expert
#   RELAY=1                 tunnel each axon out through the public relay
#   MODEL=<hf-id>           force one model on every card, default per-VRAM
#   MAX_CARDS=4             hard cap regardless of what fits
#   RESERVE_MB=4096         host RAM to keep free, default 2048
#
[[ -t 1 ]] && . /hive/miners/custom/proteus/h-manifest.conf 2>/dev/null
. /hive/miners/custom/proteus/h-manifest.conf 2>/dev/null

CONF="$CUSTOM_CONFIG_FILENAME"
mkdir -p "$(dirname "$CONF")" "$(dirname "$CUSTOM_LOG_BASENAME")"

# Defaults. Anything below can be overridden from the flight sheet.
WALLET_NAME="${CUSTOM_TEMPLATE:-miner}"
RPC="${CUSTOM_URL:-wss://rpc.proteus-agent.com}"
HOTKEY_PREFIX="expert"
GPUS=""
RELAY=0
MODEL=""
MAX_CARDS=0
RESERVE_MB=2048

# The user config box is free text. Accept KEY=VALUE, one per line or space
# separated, and ignore anything we do not know rather than failing the start.
if [[ -n "$CUSTOM_USER_CONFIG" ]]; then
  while read -r kv; do
    [[ -z "$kv" || "$kv" == \#* ]] && continue
    k="${kv%%=*}"; v="${kv#*=}"
    case "${k^^}" in
      GPUS)          GPUS="$v" ;;
      HOTKEY_PREFIX) HOTKEY_PREFIX="$v" ;;
      RELAY)         RELAY="$v" ;;
      MODEL)         MODEL="$v" ;;
      MAX_CARDS)     MAX_CARDS="$v" ;;
      RESERVE_MB)    RESERVE_MB="$v" ;;
      WALLET_NAME)   WALLET_NAME="$v" ;;
      *) echo "proteus: ignoring unknown key '$k'" ;;
    esac
  done < <(echo "$CUSTOM_USER_CONFIG" | tr ' ' '\n')
fi

cat > "$CONF" <<EOF
# Generated by h-config.sh, do not edit: rewritten on every start.
WALLET_NAME="$WALLET_NAME"
RPC="$RPC"
HOTKEY_PREFIX="$HOTKEY_PREFIX"
GPUS="$GPUS"
RELAY="$RELAY"
MODEL="$MODEL"
MAX_CARDS="$MAX_CARDS"
RESERVE_MB="$RESERVE_MB"
EOF

echo "proteus: config written to $CONF"
